<?php

/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/** @var \Magento\Checkout\Block\Cart\Item\Renderer $block */
$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
// @codingStandardsIgnoreLine
$helper = $this->helper(\Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
/** @var \Amasty\RequestQuote\Helper\Cart $cartHelper */
// @codingStandardsIgnoreLine
$cartHelper = $this->helper(\Amasty\RequestQuote\Helper\Cart::class);
/** @var \Amasty\RequestQuote\Helper\Data $configHelper */
// @codingStandardsIgnoreLine
$configHelper = $this->helper(\Amasty\RequestQuote\Helper\Data::class);

$blockObj = $block->getLayout()->createBlock('Magemonkeys\Customerinfo\Block\Customerinfo');
$customerGroupId = $blockObj->getGroupId();
$toolTipHelper = $this->helper('Eagle\Tooltip\Helper\Config\TooltipConfig');
$helperMagemonkeys = $this->helper('Magemonkeys\Quote\Helper\Data');
$mou = $helperMagemonkeys->getProductSize($item->getSku());
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $escaper->escapeHtml(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()) : ?>
        <a href="<?= /* @noEscape */ $block->getProductUrl() ?>" title="<?= $escaper->escapeHtml($block->getProductName()) ?>" tabindex="-1" class="product-item-photo">
            <?php else : ?>
            <span class="product-item-photo">
                    <?php endif; ?>
                    <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                    <?php if ($block->hasProductUrl()) : ?>
        </a>
    <?php else : ?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) : ?>
                    <a href="<?= /* @noEscape */ $block->getProductUrl() ?>"><?= $escaper->escapeHtml($block->getProductName()) ?></a>
                <?php else : ?>
                    <?= $escaper->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($options = $block->getOptionList()) : ?>
                <dl class="item-options">
                    <?php foreach ($options as $option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                <?= /* @noEscape */ $_formatedOptionValue['full_view'] ?>
                            <?php else : ?>
                                <?= /* @noEscape */ $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <!-- <div>
                <a class="add-note-quote"><?= $escaper->escapeHtml(__('Add Note')) ?></a>
                <div class="field textarea add-note">
                    <div class="control">
                    <textarea id="cart-<?= /* @noEscape */ $item->getId() ?>-note"
                              name="cart[<?= /* @noEscape */ $item->getId() ?>][note]"
                              data-cart-item-id="<?= $escaper->escapeHtml($item->getSku()) ?>"
                              rows="3"
                              cols="25"><?= $escaper->escapeHtml($cartHelper->retrieveCustomerNote($item->getAdditionalData())) ?></textarea>
                    </div>
                </div>
            </div> -->
            <?php if ($messages = $block->getMessages()) : ?>
                <?php foreach ($messages as $message) : ?>
                    <div class="cart item message <?= /* @noEscape */ $message['type'] ?>">
                        <div><?= $escaper->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) : ?>
                <?= $addInfoBlock->setItem($item)->toHtml() ?>
            <?php endif; ?>
        </div>
    </td>
    <?php if ($customerGroupId != 9 && $customerGroupId != 0) : ?>
        <?php if ($product->getPrice() > 0.01) : ?>
            <td class="col price qty" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $product = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getProductId());
                $specilaQty = $toolTipHelper->getSpecialPriceQtyByCustomerGroup($product->getSku(), $customerGroupId);
                if ($specilaQty !== null) {
                    $specilaQty = rtrim(rtrim($specilaQty, '0'), '.');
                }
                ?>
                <?php if ($toolTipHelper->tierPriceByCustomerId($product->getSku(), $customerGroupId) != null) : ?>
                    <?= $toolTipHelper->getTierPriceByQty($item->getSku(), $customerGroupId, $item->getQty()) ?>
                <?php else : ?>
                    <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($product->getPrice(), true, false); ?>
                <?php endif; ?>

            </td>
        <?php else : ?>
            <td class="col price qty"><?= $escaper->escapeHtml('N/A') ?></td>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($canApplyMsrp) : ?>
        <td class="col msrp" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= /* @noEscape */ __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @noEscape */ ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @noEscape */ $helpLinkId ?>","productName": "<?= /* @noEscape */ $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @noEscape */ __("What's this?") ?></span>
                    </a>
                </span>
        </td>
    <?php else : ?>
        <td class="col price qty aaaa" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
            <?php

            $data = json_decode($item->getAdditionalData(), true);
            $requestedPrice = 'N/A';
            if (isset($data['requested_custom_price']) && $data['requested_custom_price'] !== 0) {
                if ($data['requested_custom_price'] !== '') {
                    $requestedPrice = $data['requested_custom_price'];
                }
            }
            ?>
            <?php if ($toolTipHelper->tierPriceByCustomerId($product->getSku(), $customerGroupId) != null) : ?>
                <div class="field price">
                    <div class="control price">
                        $
                        <input id="cart-<?= $item->getId() ?>-price" name="cart[<?= $item->getId() ?>][price]" value="<?= $requestedPrice ?>" size="4" title="Price" class="input-text price amquotereq-input" data-role="cart-item-price">
                    </div>
                </div>
            <?php else : ?>
                <?php if (
                    $customerGroupId != 0 &&
                    $item->getPrice() != 0.01
                    && $requestedPrice != "N/A"
                ) : ?>
                    <?= $block->getUnitPriceHtml($item) ?>
                <?php else : ?>
                    <div class="field price">
                        <div class="control price">
                            $
                            <input id="cart-<?= $item->getId() ?>-price" name="cart[<?= $item->getId() ?>][price]" value="N/A" size="4" title="Price" class="input-text price amquotereq-input" data-role="cart-item-price">
                        </div>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <label class="label" for="cart-<?= /* @noEscape */ $item->getId() ?>-qty">
                <span><?= /* @noEscape */ __('Qty') ?></span>
            </label>
            <div class="control qty">
                <input id="cart-<?= /* @noEscape */ $item->getId() ?>-qty" name="cart[<?= /* @noEscape */ $item->getId() ?>][qty]" data-cart-item-id="<?= $escaper->escapeHtml($item->getSku()) ?>" value="<?= /* @noEscape */ $block->getQty() ?>" type="number" size="4" title="<?= $escaper->escapeHtml(__('Qty')) ?>" class="input-text qty" data-validate="{required:true,'validate-greater-than-zero':true}" data-role="cart-item-qty" />
            </div>
        </div>
    </td>

    <td class="item-uom"><?= /* @noEscape */ $mou ?></td>

    <?php if ($customerGroupId != 9 && $customerGroupId != 0) : ?>
        <?php if ($product->getPrice() > 0.01) : ?>
            <td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')) ?>">
                <?php if ($canApplyMsrp) : ?>
                    <span class="cart msrp subtotal">--</span>
                <?php else : ?>

                    <?php if ((float) $item->getPrice() || $configHelper->isAllowCustomizePrice()) : ?>
                        <?php if ($item->getPrice() != 0.01) { ?>
                            <?php if ($toolTipHelper->tierPriceByCustomerId($product->getSku(), $customerGroupId) != null) : ?>
                                <?= $block->getRowTotalHtml($item) ?>
                            <?php else : ?>
                                <span class="price-excluding-tax" data-label="Excl. Tax">
                                        <span class="cart-price">
                                            <span class="price">$<?= $product->getPrice() * $item->getQty()  ?></span> </span>
                                    </span>
                            <?php endif; ?>
                        <?php } else { ?>
                            <span class="price-excluding-tax" data-label="Excl. Tax">
                                    <span class="cart-price">
                                        <span class="price">$0.00</span> </span>

                                </span>
                        <?php } ?>
                    <?php else : ?>
                        <?= $escaper->escapeHtml('N/A') ?>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
        <?php else : ?>
            <td class="col subtotal"><?= $escaper->escapeHtml('N/A') ?></td>
        <?php endif; ?>
    <?php endif; ?>
</tr>
<tr class="item-actions">
    <td colspan="100">
        <div class="actions-toolbar">
            <?= /* @noEscape */ $block->getActions($item) ?>
        </div>
    </td>
</tr>
</tbody>
<style type="text/css">
    .amasty_quote-cart-index .cart.table-wrapper .actions-toolbar>.action-edit {
        display: none;
    }
</style>
