<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper">
    <?php
    $customerSession = $this->helper('Eagle\Common\Helper\Data')->getCustomerSession();
    $customerGroupId = $customerSession->getCustomerGroupId();
    if ($customerGroupId != 9 && $customerGroupId != 10 && $customerGroupId != 11) :
    ?>
        <a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>" data-bind="scope: 'minicart_content'">
            <span class="text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
            <span class="price-label" data-bind="html: getCartParam('subtotal')">
                <!-- ko if: getCartParam('subtotal') -->
                <!-- ko text: getCartParam('subtotal') --><!-- /ko -->
                <!-- /ko -->
                <!-- ko ifnot: getCartParam('subtotal') -->
                <!-- ko i18n: '0.00' --><!-- /ko -->
                <!-- /ko -->
            </span>
            <span class="counter qty empty" data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                <span class="counter-number">
                    <!-- ko ifnot: getCartParam('summary_count') -->
                    <!-- ko i18n: '0 ' --><!-- /ko -->
                    <!-- /ko -->
                    <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                    <!-- /ko -->
                </span>
                <span class="counter-label">
                    <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                    <!-- ko i18n: 'items' --><!-- /ko -->
                    <!-- /ko -->
                </span>
            </span>
        </a>
        <?php if ($block->getIsNeedToDisplaySideBar()) : ?>
            <div class="block block-minicart empty" data-role="dropdownDialog" data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
                <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
                <?php echo $block->getChildHtml('minicart.addons'); ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
        {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>

<?php
if ($customerGroupId == 9 || $customerGroupId == 0) :
?>
    <style type="text/css">
        #quote-cart span.price {
            display: none;
            visibility: hidden;
        }
    </style>
<?php endif; ?>

<?php if ($customerGroupId == 0) :?>
    <style type="text/css">
        header.page-header.sticky-menu.active .minicart-wrapper {
            display: none;
            visibility: hidden;
        }
    </style>
<?php endif; ?>