<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$_product = $block->getPriceType('final_price')->getProduct();
$toolTipHelper = $this->helper('Eagle\Tooltip\Helper\Config\TooltipConfig');
?>

<?php if ($toolTipHelper->hasAdvancedPrice($_product)) : ?>
    <?php if (number_format($_product->getPrice(),  2, '.', '') == 0.01) : ?>
        <div class="tooltip-container">
            <div class="tooltip-icon baseuser">
                <span class="tooltip-question-mark">?</span>
            </div>
            <div class="tooltip-content">Request a quote.</div>
        </div>
    <?php else : ?>
        <?php if ($toolTipHelper->getLowestTierPriceForCustomerGroup($_product->getSku()) != null) : ?>
            <span class="advance-price"><?= '$' . number_format($toolTipHelper->getLowestTierPriceForCustomerGroup($_product->getSku()),  2, '.', '') . '<br/>'; ?></span>
            <div class="tooltip-container-special-price">
                <div class="tooltip-icon-special-price">
                    <span class="tooltip-question-mark-special-price">$</span>
                </div>
                <div class="tooltip-content-special-price"><?= $toolTipHelper->getSpecialPriceText(); ?></div>
            </div>
        <?php endif; ?>
    <?php endif; ?>

<?php else : ?>
    <?php if ($block->hasSpecialPrice()) : ?>
        <span class="special-price">
            <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __('Special Price'),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
        <span class="old-price">
            <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Regular Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </span>
    <?php else : ?>
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    <?php endif; ?>

    <?php if ($block->showMinimalPrice()) : ?>
        <?php if ($block->getUseLinkForAsLowAs()) : ?>
            <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
                <?= /* @noEscape */ $block->renderAmountMinimal() ?>
            </a>
        <?php else : ?>
            <span class="minimal-price-link">
                <?= /* @noEscape */ $block->renderAmountMinimal() ?>
            </span>
        <?php endif ?>
    <?php endif; ?>
<?php endif; ?>