<?php
/** @var \Ulmod\Ordernotes\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history um-custom-orders-history">
         <!-- Order Filters -->
                <div class="row">
                    <form method='get' >
                        <div class="filter-row col-lg-8">
                            <div scope="col" class="col id" style="font-size: 14px;"><?= $block->escapeHtml(__('Order #')) ?></div>
                            <div >
                                <input type="text" name="order_id" placeholder="Search Order No" value="<?= $this->getRequest()->getParam('order_id')?>" style="border-radius: 3px;" />
                            </div>
                        </div>

                        <div class="filter-row col-lg-8">
                            <div scope="col" class="col id"  style="font-size: 14px;"><?= /* @escapeNotVerified */ __('Product Name') ?></div>
                            <div scope="col" class="col products-name" >
                                <input type="text" placeholder="Search Name" name="name" value="<?= $this->getRequest()->getParam('name')?>" style="border-radius: 3px;" />
                            </div>
                        </div>

                        <div class="filter-row col-lg-8">
                            <div scope="col" class="col id"  style="font-size: 14px;"><?= /* @escapeNotVerified */ __('Product SKU') ?></div>
                            <div scope="col" class="col products-sku" >
                                <input type="text" placeholder="Search SKU" name="sku" value="<?= $this->getRequest()->getParam('sku')?>" style="border-radius: 3px;" />
                            </div>
                        </div>

                        <div class="filter-row col-lg-16"  style="padding-top: 10px;padding-bottom: 10px;">
                            <div scope="col" class="col date"  style="font-size: 14px;"><?= $block->escapeHtml(__('Date')) ?></div>
                        <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ?>   
                            <div scope="col" class="col date row" id="calendar_inputField" >
                                <div class="col-lg-12">
                                    <input type="text" placeholder="From" id="date-from" name="from_date" value="<?= $this->getRequest()->getParam('from_date')?>" style="border-radius: 3px;" />
                                </div>
                                <div class="col-lg-12">
                                    <input type="text" id="date-to" name="to_date"   placeholder="To" value="<?= $this->getRequest()->getParam('to_date')?>" style="border-radius: 3px;" />
                                </div>
                            </div> 
                        </div>

                        <div class="filter-row col-lg-8"  style="padding-top: 10px;padding-bottom: 10px;">
                            <div scope="col" class="col total"  style="font-size: 14px;"><?= $block->escapeHtml(__('Order Total')) ?></div>                     
                            <div scope="col" class="col total" >
                                <input type="text" name="grand_total" placeholder="Search Order Total" value="<?= $this->getRequest()->getParam('grand_total')?>" style="border-radius: 3px;" />
                            </div> 
                        </div>  

                        <div class="filter-row col-lg-8">
                            <div scope="col" class="col po"  style="font-size: 14px;"><?= $block->escapeHtml(__('Purchase Order')) ?></div>                     
                            <div scope="col" class="col po" >
                                <input type="text" name="po_number" placeholder="Search Purchase Order" value="<?= $this->getRequest()->getParam('po_number')?>" style="border-radius: 3px;" />
                            </div> 
                        </div>  

                        <div class="filter-row col-lg-8">
                            <div scope="col" class="col actions"  style="font-size: 14px;"><?= $block->escapeHtml(__('Action')) ?></div>                       
                            <div scope="col" class="col actions" >
                                <input class="action primary" type="submit" value="Click Here to Apply Filter"  style="width: 100%;border-radius: 3px;"  />
                            </div>
                        </div>
                    </form>
                </div>
                <!-- Order Filters -->
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>               
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <!-- Order Filters -->
                    <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                    <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Product SKU') ?></th>
                    <!-- Order Filters -->
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Ship To')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col po"><?= /* @escapeNotVerified */ __('Purchase Order #') ?></th>
                    <th scope="col" class="col order-note-col">
                        <?= $block->escapeHtml(__('Order Note')) ?>
                    </th>                    
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>

            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id">
                            <?= /* @noEscape */ $_order->getRealOrderId() ?>
                        </td>
                        <!-- Order Filters -->
                        <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col name">
                            <?= /* @escapeNotVerified */ $block->getProductName($_order) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Product Sku')) ?>" class="col sku">
                            <?= /* @escapeNotVerified */ $block->getProductSku($_order) ?>
                        </td>
                        <!-- Order Filters -->
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date">
                            <?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?>
                        </td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= /* @noEscape */ $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping">
                            <?= $_order->getShippingAddress() ?
                            $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total">
                            <?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                            <?= /* @noEscape */ $_order->getStatusLabel() ?>            
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Purchase Order #')) ?>" class="col purchaseorder"><?= /* @escapeNotVerified */ $_order->getPayment()->getPoNumber() ?></td>  
                        <td data-th="<?= $block->escapeHtml(__('Order Notes')) ?>" class="col um-order-notes"> 
                        <?php
                            $lastNoteByOrder = $block->getLastNoteByOrder($_order);
                            $orderNotesReadUrl = $block->getOrderNotesReadUrl($_order);
                        ?>
                            <input type="hidden" name="um_orderid" 
                                value="<?= /* @noEscape */ $_order->getEntityId(); ?>">
                            <?php if ($block->isNewMessage($lastNoteByOrder)): ?>                                     
                            <div class="um-grid-new-note um-note">
                                <?= $block->escapeHtml(__('* New message')) ?>
                            </div>     
                            <a id="um-grid-send-msg-read um-note" 
                                 onclick="setLocation(this.href)"
                                 href="<?= $block->escapeUrl($orderNotesReadUrl); ?>" 
                                 class="um-action-readnote action view">
                                 <span><?= $block->escapeHtml(__('Read message')) ?></span>
                            </a>                                         
                            <?php else: ?>                                        
                            <div class="um-grid-no-note um-note">
                                <?= $block->escapeHtml(__('No message')) ?></div>                              
                            <?php endif ?>                            
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php
                                $blockObj= $block->getLayout()->createBlock('Magemonkeys\Customerinfo\Block\Customerinfo');
                                $customerGroupId = $blockObj->getGroupId(); 
                                if ($customerGroupId != 9 && $customerGroupId != 10 && $customerGroupId != 11) {
                            ?>
                            <?php if ($block->getSalesReorder()->canReorder($_order->getEntityId())): ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                $block->getPostHelper()->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>   
                            <?php } ?>                                
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty">
        <span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span>
    </div>
<?php endif ?>

<!-- Order Filters -->
<script>
    require([
        "jquery",
        "mage/calendar"
    ], function ($) {
        $("#calendar_inputField").dateRange({
            buttonText: 'Select Date',
            changeMonth: true,
            changeYear: true,
            from: {
                id: 'date-from'
            },
            to: {
                id: 'date-to'
            }
        });
    });
</script>
<!-- Order Filters -->