<?php

/**
 * @author Amasty Team
 * @copyright Copyright (c) 2023 Amasty (https://www.amasty.com)
 * @package Request a Quote Base for Magento 2
 */
/**
 * @var $block \Amasty\RequestQuote\Block\Adminhtml\Quote\Edit\Items\Grid
 */
$toolTipHelper = $this->helper('Eagle\Tooltip\Helper\Config\TooltipConfig');
?>
<?php $items = $block->getItems() ?>
<?php if (empty($items)) : ?>
    <div id="order-items_grid">
        <div class="admin__table-wrapper">
            <table class="data-table admin__table-primary order-tables">
                <thead>
                    <tr class="headings">
                        <th class="col-product"><span><?= $escaper->escapeHtml(__('Product')) ?></span></th>
                        <th class="col-price"><span><?= $escaper->escapeHtml(__('Price')) ?></span></th>
                        <th class="col-requested_price"><span><?= $escaper->escapeHtml(__('Requested Price')) ?></span></th>
                        <th class="col-qty"><span><?= $escaper->escapeHtml(__('Requested Qty')) ?></span></th>
                        <th class="col-qty available-admin"><span><?= $escaper->escapeHtml(__('Available Qty')) ?></span></th>
                        <th class="col-subtotal"><span><?= $escaper->escapeHtml(__('Subtotal')) ?></span></th>
                        <th class="col-row-total"><span><?= $escaper->escapeHtml(__('Row Subtotal')) ?></span></th>
                        <th class="col-action"><span><?= $escaper->escapeHtml(__('Action')) ?></span></th>
                        <th class="col-note"><span><?= $escaper->escapeHtml(__('Note')) ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="even">
                        <td class="empty-text" colspan="100"><?= $escaper->escapeHtml(__('No ordered items')) ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php else : ?>
    <div class="admin__table-wrapper" id="order-items_grid">
        <?php if (count($items) > 10) : ?>
            <div class="actions update actions-update">
                <?= $block->getButtonHtml(__('Update Items and Quantities'), 'quote.itemsUpdate()', 'action-secondary') ?>
            </div>
        <?php endif; ?>
        <table class="data-table admin__table-primary order-tables">
            <thead>
                <tr class="headings">
                    <th class="col-product"><span><?= $escaper->escapeHtml(__('Product')) ?></span></th>
                    <th class="col-price"><span><?= $escaper->escapeHtml(__('Price') . ' ('
                                                    . ($block->priceIncludesTax() ? __('Incl. Tax') : __('Excl. Tax')) . ')') ?></span></th>
                    <th class="col-requested_price"><span><?= $escaper->escapeHtml(__('Requested Price')) ?></span></th>
                    <th class="col-qty"><span><?= $escaper->escapeHtml(__('Requested Qty')) ?></span></th>
                    <th class="col-qty available-admin"><span><?= $escaper->escapeHtml(__('Available Qty')) ?></span></th>
                    <th class="col-row-total"><span><?= $escaper->escapeHtml(__('Row Subtotal')) ?></span></th>
                    <th class="col-action"><span><?= $escaper->escapeHtml(__('Action')) ?></span></th>
                    <th class="col-approve-item"><span><?= $escaper->escapeHtml(__('Approve Item')) ?></span></th>
                    <th class="col-note"><span><?= $escaper->escapeHtml(__('Note')) ?></span></th>
                    <th class="col-cancel-date"><span><?= $escaper->escapeHtml(__('Cancelled Date')) ?></span></th>
                    <th class="col-email-subject"><span><?= $escaper->escapeHtml(__('Email Subject Content')) ?></span></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td class="col-total"><?= $escaper->escapeHtml(__('Total %1 product(s)', count($items))) ?></td>
                    <td colspan="2" class="col-subtotal"><?= $escaper->escapeHtml(__('Subtotal:')) ?></td>
                    <td class="col-price"><strong><?= /* @noEscape */ $block->formatPrice($block->getSubtotal()) ?></strong></td>
                    <td class="col-price"><strong><?= /* @noEscape */ $block->formatPrice($block->getSubtotalWithDiscount()); ?></strong></td>
                    <td colspan="2">&nbsp;</td>
                </tr>
            </tfoot>
            <?php $i = 0 ?>
            <?php foreach ($items as $item) : $i++ ?>
                <tbody class="<?= /* @noEscape */ ($i % 2) ? 'even' : 'odd' ?>">
                    <tr>
                        <td class="col-product">
                            <span id="order_item_<?= $escaper->escapeHtml($item->getId()) ?>_title"><?= $escaper->escapeHtml($item->getName()) ?></span>
                            <div class="product-sku-block">
                                <span><?= $escaper->escapeHtml(__('SKU')) ?>:</span>
                                <?= $block->getSkuHtml($item->getSku()) ?>
                            </div>
                            <div class="product-configure-block">
                                <?= $block->getConfigureButtonHtml($item) ?>
                            </div>
                        </td>
                        <td class="col-price">
                            <div class="price-excl-tax">
                                <?php if ($toolTipHelper->tierPriceByCustomerId($item->getProduct()->getSku(), $block->getCustomerGroupId()) != null) : ?>
                                    <?= $toolTipHelper->getTierPriceByQty($item->getSku(), $block->getCustomerGroupId(), $item->getQty()) ?>
                                <?php else : ?>
                                    <?= /* @noEscape */ $block->formatPrice($item->getProduct()->getFinalPrice(), true); ?>
                                <?php endif; ?>

                            </div>
                            <?php if ($tier = $block->getTierHtml($item)) : ?>
                                <div id="item_tier_block_<?= $escaper->escapeHtml($item->getId()) ?>">
                                    <a href="#" onclick="$('item_tier_<?= $escaper->escapeHtml($item->getId()) ?>').toggle();return false;"><?= $escaper->escapeHtml(__('Tier Pricing')) ?></a>
                                    <div style="display:none" id="item_tier_<?= $escaper->escapeHtml($item->getId()) ?>"><?= /* @noEscape */ $tier ?></div>
                                </div>
                            <?php endif; ?>
                            <input id="itemprice_<?= $escaper->escapeHtml($item->getId()) ?>" name="item[<?= $escaper->escapeHtml($item->getId()) ?>][price]" value="<?= $escaper->escapeHtml(sprintf("%.2f", $block->getItemEditablePrice($item))) ?>" class="input-text item-price admin__control-text" style="width: 100px;" />
                        </td>
                        <?php

                        $data = json_decode($item->getAdditionalData(), true);
                        $requestedPrice = 'N/A';
                        if (isset($data['requested_price'])) {
                            if ($data['requested_price'] !== '') {
                                $requestedPrice = $data['requested_price'];
                            }
                        }
                        ?>
                        <td class="col-requested_price">
                            <input name="item[<?= $escaper->escapeHtml($item->getId()) ?>][requested_price]" class="input-text item-qty admin__control-text" value="<?= $requestedPrice ?>" maxlength="12" style="width: 100px;" />
                        </td>

                        <td class="col-qty">
                            <input name="item[<?= $escaper->escapeHtml($item->getId()) ?>][requested_qty]" class="input-text item-qty admin__control-text" 
                                value="<?= $item->getQty() * 1 ?>" 
                                maxlength="12" />
                        </td>

                        <td class="col-qty" style="display: none;">
                            <input name="item[<?= $escaper->escapeHtml($item->getId()) ?>][qty]" class="input-text item-qty admin__control-text" value="<?= $item->getQty() * 1 ?>" maxlength="12" />
                        </td>

                        <td class="col-qty available-admin">
                            <?php
                            $availableQty = $item->getAvailableQty() * 1;
                            $displayValue = $availableQty != 0 ? $availableQty : '-';
                            ?>
                            <input name="item[<?= $escaper->escapeHtml($item->getId()) ?>][available_qty]" class="input-text available-item-qty admin__control-text" value="<?= $displayValue ?>" maxlength="12" />
                        </td>

                        <td class="col-price col-row-subtotal">
                            <div class="price-excl-tax">
                                <span class="label">Excl. Tax:</span>
                                <span class="price"><?= $block->getItemRowTotalWithDiscountHtml($item) ?></span>
                            </div>
                            <div class="price-incl-tax">
                                <span class="label">Incl. Tax:</span>
                                <span class="price"><?= $block->getItemInclTotalWithDiscountHtml($item) ?></span>
                            </div>
                        </td>
                        <td class="col-actions last">
                            <select class="admin__control-select" name="item[<?= $escaper->escapeHtml($item->getId()) ?>][action]">
                                <option value=""><?= $escaper->escapeHtml(__('Please select')) ?></option>
                                <option value="remove"><?= $escaper->escapeHtml(__('Remove')) ?></option>
                            </select>
                        </td>

                        <td class="col-approve-item approval-status">
                            <select id="approval_status" name="item[<?= $escaper->escapeHtml($item->getId()) ?>][approval_status]" class="admin__control-select">
                                <option value="0" <?php if ($item->getApprovalStatus() == '0') echo 'selected'; ?>>Pending</option>
                                <option value="1" <?php if ($item->getApprovalStatus() == '1') echo 'selected'; ?>>Approved Item</option>
                                <option value="2" <?php if ($item->getApprovalStatus() == '2') echo 'selected'; ?>>Cancelled By Customer</option>
                                <option value="3" <?php if ($item->getIsCancelByAdmin() == '3') echo 'selected'; ?>>Cancelled By Admin</option>
                            </select>
                        </td>

                        <td class="col-note">
                            <textarea name="item[<?= $escaper->escapeHtml($item->getId()) ?>][quote_note]" rows="4" cols="25"><?= $escaper->escapeHtml($item->getQuoteNote()) ?></textarea>
                        </td>

                        <td class="col-cancel-date">
                            <?php if ($item->getCancelledDate()) : ?>
                                <span><strong><?= $escaper->escapeHtml($item->getCancelledDate()) ?></strong></span>
                            <?php endif; ?>
                        </td>


                        <?php if ($i === 1) : ?>
                            <td class="col-email subject-content">
                                <textarea rows="3" cols="20" name="item[<?= $escaper->escapeHtml($item->getId()) ?>][email_subject]"><?= $escaper->escapeHtml($item->getEmailSubject()) ?></textarea>
                            </td>
                        <?php endif; ?>

                    </tr>
                    <?php if ($itemQuestion = $block->getItemQuestion($item)) : ?>
                        <tr class="row-notes-error">
                            <td colspan="2">
                                <strong><?= $escaper->escapeHtml(__('Customer Note:')) ?></strong>
                                <div class="customer-note">
                                    <?= /* @noEscape */ nl2br($escaper->escapeHtml($itemQuestion)) ?>
                                </div>
                            </td>
                            <td colspan="10">
                                <?php if ($answer = $block->getItemAnswer($item)) : ?>
                                    <strong><?= $escaper->escapeHtml(__('Administrator Note:')) ?></strong>
                                    <div class="customer-note">
                                        <?= /* @noEscape */ nl2br($escaper->escapeHtml($answer)) ?>
                                    </div>
                                <?php else : ?>
                                    <strong><?= $escaper->escapeHtml(__('Administrator Note:')) ?></strong>
                                    <div class="control">
                                        <a class="add-note-quote-item"><?= $escaper->escapeHtml(__('Add Note')) ?></a>
                                        <div class="textarea-control" style="display: none;">
                                            <textarea name="item[<?= $escaper->escapeHtml($item->getId()) ?>][note]" rows="2" cols="50"></textarea>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endif; ?>

                    <?php $hasMessageError = false; ?>
                    <?php foreach ($item->getMessage(false) as $messageError) : ?>
                        <?php if (!empty($messageError)) {
                            $hasMessageError = true;
                        }
                        ?>
                    <?php endforeach; ?>
                    <!--
                    <?php if ($hasMessageError) : ?>
                        <tr class="row-messages-error">
                            <td colspan="100">
                                <?php foreach ($item->getMessage(false) as $message) :
                                    if (empty($message)) {
                                        continue;
                                    }
                                ?>
                                    <div class="message <?php if ($item->getHasError()) : ?>message-error<?php else : ?>message-notice<?php endif; ?>">
                                        <?= $escaper->escapeHtml($message) ?>
                                    </div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    <?php endif; ?> -->
                </tbody>
            <?php endforeach; ?>
        </table>
    </div>

    <?php if ($block->getAppliedDiscount() || $block->getAppliedSurcharge()) : ?>
        <div class="amquote-line-block amquote-approved-title">
            <p class="amquote-title">
                <?= $escaper->escapeHtml(__('Applied') . ' ' . ($block->getAppliedSurcharge() ? __('surcharge') : __('discount')) . ': ') ?>
                <strong>
                    <?= /* @noEscape */ ($block->getAppliedSurcharge() ? $block->getAppliedSurcharge() : $block->getAppliedDiscount()) . '%' ?>
                </strong>
            </p>

            <button class="action-secondary" type="button" onclick="quote.removeModificators()">
                <?= $escaper->escapeHtml(__('Remove') . ' ' . ($block->getAppliedSurcharge() ? __('surcharge') : __('discount'))) ?>
            </button>
        </div>
    <?php endif; ?>

    <div class="amquote-order-discount">
        <div id="order-coupons" class="amquote-coupons"><?= $block->getChildHtml() ?></div>
        <?= $block->getButtonHtml(__('Update Items and Quantities'), 'quote.itemsUpdate()', 'action-secondary') ?>
    </div>
<?php endif; ?>