<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /** @var $block \Magento\Framework\Pricing\Render\Amount */ ?>
<?php
$blockObj = $block->getLayout()->createBlock('Magemonkeys\Customerinfo\Block\Customerinfo');
$customerGroupId = $blockObj->getGroupId();
?>
<?php if ($block->getDisplayValue() > 0.01) : ?>
    <?php if ($customerGroupId != 9) : ?>
        <span class="price-container <?= $block->escapeHtmlAttr($block->getAdjustmentCssClasses()) ?>" <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
            <?php if ($block->getDisplayLabel()) : ?>
                <span class="price-label"><?= $block->escapeHtml($block->getDisplayLabel()) ?></span>
            <?php endif; ?>
            <span <?php if ($block->getPriceId()) : ?> id="<?= $block->escapeHtmlAttr($block->getPriceId()) ?>" <?php endif; ?> <?= ($block->getPriceDisplayLabel()) ? 'data-label="' . $block->escapeHtmlAttr($block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes()) . '"' : '' ?> data-price-amount="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>" data-price-type="<?= $block->escapeHtmlAttr($block->getPriceType()) ?>" class="price-wrapper <?= $block->escapeHtmlAttr($block->getPriceWrapperCss()) ?>"><?= $block->escapeHtml($block->formatCurrency($block->getDisplayValue(), (bool)$block->getIncludeContainer()), ['span']) ?></span>
            <?php if ($block->hasAdjustmentsHtml()) : ?>
                <?= $block->getAdjustmentsHtml() ?>
            <?php endif; ?>
            <?php if ($block->getSchema()) : ?>
                <meta itemprop="price" content="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>" />
                <meta itemprop="priceCurrency" content="<?= $block->escapeHtmlAttr($block->getDisplayCurrencyCode()) ?>" />
            <?php endif; ?>
        </span>
    <?php else : ?>
        <div class="tooltip-container">
            <div class="tooltip-icon baseuser">
                <span class="tooltip-question-mark">?</span>
            </div>
            <div class="tooltip-content">Please note that list prices are subject to change based on market conditions. Request a quote for accurate pricing for this product.</div>
        </div>
    <?php endif; ?>
<?php else : ?>
    <div class="tooltip-container">
        <div class="tooltip-icon baseuser">
            <span class="tooltip-question-mark">?</span>
        </div>
        <div class="tooltip-content">Please note that list prices are subject to change based on market conditions. Request a quote for accurate pricing for this product.</div>
    </div>
<?php endif; ?>
<style>
    .tooltip-icon.baseuser {
        margin-top: -2px !important;
    }
</style>