<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php
$stockItem = $_product->getExtensionAttributes()->getStockItem();
$quantity = $stockItem->getQty();
?>
<?php
$qtyIncrements = 1;
$dataValidate = $block->getQuantityValidators();
if (isset($dataValidate["validate-item-quantity"]["qtyIncrements"])) {
    $qtyIncrements = $dataValidate["validate-item-quantity"]["qtyIncrements"];
}
?>
<?php $buttonTitle = __('Add to Cart'); ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) : ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                <div class="control">
                    <div class="qty-minus"> <a class="btn-qty minus" href="#">-</a></div>
                    <div class="qty-input">
                        <input type="number" name="qty" id="qty" maxlength="12" value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />
                    </div>
                    <div class="qty-plus"> <a class="btn-qty plus" href="#">+</a></div>
                </div>
            </div>
            <script type="text/javascript">
                require(['jquery', 'domReady!'], function($) {
                    var dataValidate = $('#qty').data('validate');
                    var qtyIncrements = 1;
                    if (dataValidate["validate-item-quantity"]["qtyIncrements"] != null) {
                        qtyIncrements = dataValidate["validate-item-quantity"]["qtyIncrements"]
                    }
                    $(".btn-qty").click(function(event) {
                        var $button = $(this);
                        var oldValue = $button.closest('.control').find("input#qty").val();
                        var defaultValue = <?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>;
                        if ($button.hasClass('plus')) {
                            var newVal = parseFloat(oldValue) + qtyIncrements;
                        } else {
                            if (oldValue > defaultValue) {
                                var newVal = parseFloat(oldValue) - qtyIncrements;
                            } else {
                                newVal = defaultValue;
                            }
                        }
                        $button.closest('.control').find("input#qty").val(newVal);
                        event.preventDefault();
                    });

                });
            </script>
        <?php endif; ?>
        <div class="cms-block" style="padding: 63px 0px 0px 0px;">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product-page-block')->toHtml(); ?>
        </div>

        <div class="actions">
            <?php
            $blockObj = $block->getLayout()->createBlock('Magemonkeys\Customerinfo\Block\Customerinfo');
            $customerGroupId = $blockObj->getGroupId();
            if ($customerGroupId != 0 && $customerGroupId != 9 && $customerGroupId != 10 && $customerGroupId != 11) {
            ?>
                <?php
                $commonHelper = $this->helper('Eagle\Common\Helper\Data')->getCustomerSession();
                if ($commonHelper->isLoggedIn()) :
                ?>
                    <?php if ($_product->getPrice() > 0.01 && $quantity != 0) { ?>
                        <button type="submit" title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>" class="action primary tocart" id="product-addtocart-button">
                            <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                        </button>
                    <?php } ?>
                <?php endif; ?>
            <?php } ?>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function($) {
            'use strict';

            $('[id="product_addtocart_form"]').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function(form) {
                    // var widget = $(form).catalogAddToCart({
                    //     bindSubmit: false
                    // });

                    // widget.catalogAddToCart('submitForm', $(form));

                    // return false;
                }
            });

            $(document).ready(function() {
                $('#product-addtocart-button').click(function(e) {
                    var form = $('#product_addtocart_form');
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form), 'product-addtocart-button');

                    return false;
                });

                $('#product-addtoquote').click(function(e) {
                    var form = $('#product_addtocart_form');
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form), 'product-addtoquote');

                    return false;
                });
            });
        });
    </script>
<?php endif; ?>